import { WardrobeItem, MainCategory } from '@/lib/types';

export interface SampleItemSeed {
  name: string;
  category: MainCategory;
  subcategory: string;
  image_url: string;
  primary_color: string;
  secondary_colors: string[];
  pattern: string;
  material: string;
  fit: string;
  style: string;
  formality: 'Casual' | 'Smart Casual' | 'Semi-Formal' | 'Formal' | 'Festive';
  season: string[];
  is_favorite?: boolean;
}

export const SAMPLE_INDIAN_WARDROBE: SampleItemSeed[] = [
  // TOPS
  {
    name: 'Crisp White Linen Shirt',
    category: 'tops',
    subcategory: 'shirt',
    image_url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    primary_color: 'White',
    secondary_colors: ['Off-White'],
    pattern: 'Solid',
    material: 'Pure Linen',
    fit: 'Regular',
    style: 'Smart Casual',
    formality: 'Smart Casual',
    season: ['Summer', 'Monsoon', 'All-Season'],
    is_favorite: true,
  },
  {
    name: 'Sky Blue Oxford Button-Down',
    category: 'tops',
    subcategory: 'shirt',
    image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Light Blue',
    secondary_colors: ['Navy'],
    pattern: 'Solid',
    material: '100% Cotton Oxford',
    fit: 'Regular',
    style: 'Smart Casual',
    formality: 'Semi-Formal',
    season: ['All-Season', 'Summer'],
    is_favorite: true,
  },
  {
    name: 'Olive Green Textured Overshirt',
    category: 'tops',
    subcategory: 'overshirt',
    image_url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Olive Green',
    secondary_colors: ['Khaki'],
    pattern: 'Textured',
    material: 'Cotton Twill',
    fit: 'Relaxed',
    style: 'Casual',
    formality: 'Casual',
    season: ['All-Season', 'Winter'],
    is_favorite: false,
  },
  {
    name: 'Charcoal Pique Polo',
    category: 'tops',
    subcategory: 'polo',
    image_url: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Charcoal Grey',
    secondary_colors: ['Black'],
    pattern: 'Solid',
    material: 'Pique Cotton',
    fit: 'Slim',
    style: 'Smart Casual',
    formality: 'Smart Casual',
    season: ['Summer', 'All-Season'],
    is_favorite: false,
  },
  {
    name: 'Classic Navy Heavyweight T-Shirt',
    category: 'tops',
    subcategory: 't-shirt',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Navy Blue',
    secondary_colors: [],
    pattern: 'Solid',
    material: 'Heavyweight Cotton',
    fit: 'Regular',
    style: 'Minimal',
    formality: 'Casual',
    season: ['All-Season', 'Summer'],
    is_favorite: true,
  },
  {
    name: 'Sand Modern Kurta Shirt',
    category: 'tops',
    subcategory: 'kurta',
    image_url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Sand Beige',
    secondary_colors: ['Cream'],
    pattern: 'Subtle Texture',
    material: 'Linen Blend',
    fit: 'Relaxed',
    style: 'Modern Indian',
    formality: 'Smart Casual',
    season: ['Summer', 'Festive', 'All-Season'],
    is_favorite: true,
  },

  // BOTTOMS
  {
    name: 'Beige Relaxed Pleated Chinos',
    category: 'bottoms',
    subcategory: 'chinos',
    image_url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Beige',
    secondary_colors: ['Camel'],
    pattern: 'Solid',
    material: 'Cotton Gabardine',
    fit: 'Relaxed',
    style: 'Smart Casual',
    formality: 'Smart Casual',
    season: ['All-Season', 'Summer'],
    is_favorite: true,
  },
  {
    name: 'Raw Indigo Straight-Fit Jeans',
    category: 'bottoms',
    subcategory: 'jeans',
    image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Dark Indigo',
    secondary_colors: ['Navy'],
    pattern: 'Solid Denim',
    material: 'Raw Denim Cotton',
    fit: 'Regular',
    style: 'Casual',
    formality: 'Casual',
    season: ['All-Season', 'Winter', 'Monsoon'],
    is_favorite: true,
  },
  {
    name: 'Charcoal Tailored Trousers',
    category: 'bottoms',
    subcategory: 'trousers',
    image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Charcoal',
    secondary_colors: ['Black'],
    pattern: 'Solid',
    material: 'Tropical Wool Blend',
    fit: 'Tailored',
    style: 'Smart Casual',
    formality: 'Semi-Formal',
    season: ['All-Season', 'Summer'],
    is_favorite: false,
  },
  {
    name: 'Off-White Summer Linen Pants',
    category: 'bottoms',
    subcategory: 'trousers',
    image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Off-White',
    secondary_colors: ['Ivory'],
    pattern: 'Solid',
    material: 'Pure Linen',
    fit: 'Relaxed',
    style: 'Modern Indian',
    formality: 'Smart Casual',
    season: ['Summer', 'Festive'],
    is_favorite: false,
  },

  // LAYERS
  {
    name: 'Midnight Navy Bomber Jacket',
    category: 'layers',
    subcategory: 'jacket',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Navy Blue',
    secondary_colors: ['Black'],
    pattern: 'Solid',
    material: 'Lightweight Poly-Cotton',
    fit: 'Regular',
    style: 'Smart Casual',
    formality: 'Smart Casual',
    season: ['Winter', 'Monsoon', 'Evening'],
    is_favorite: true,
  },
  {
    name: 'Heather Grey Fine Knit Sweater',
    category: 'layers',
    subcategory: 'sweater',
    image_url: 'https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Grey',
    secondary_colors: ['Melange'],
    pattern: 'Textured',
    material: 'Merino Wool Blend',
    fit: 'Slim',
    style: 'Minimal',
    formality: 'Smart Casual',
    season: ['Winter'],
    is_favorite: false,
  },

  // FOOTWEAR
  {
    name: 'Minimalist White Leather Sneakers',
    category: 'footwear',
    subcategory: 'sneakers',
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    primary_color: 'White',
    secondary_colors: ['Off-White'],
    pattern: 'Solid',
    material: 'Full Grain Leather',
    fit: 'Regular',
    style: 'Minimal',
    formality: 'Smart Casual',
    season: ['All-Season', 'Summer'],
    is_favorite: true,
  },
  {
    name: 'Dark Brown Leather Penny Loafers',
    category: 'footwear',
    subcategory: 'loafers',
    image_url: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Dark Brown',
    secondary_colors: ['Mahogany'],
    pattern: 'Solid',
    material: 'Italian Calf Leather',
    fit: 'Regular',
    style: 'Smart Casual',
    formality: 'Semi-Formal',
    season: ['All-Season', 'Summer', 'Winter'],
    is_favorite: true,
  },
  {
    name: 'Tan Handcrafted Kolhapuri Slippers',
    category: 'footwear',
    subcategory: 'kolhapuris',
    image_url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Tan Brown',
    secondary_colors: ['Gold'],
    pattern: 'Braided Detail',
    material: 'Natural Vegetable-Tanned Leather',
    fit: 'Regular',
    style: 'Modern Indian',
    formality: 'Smart Casual',
    season: ['Summer', 'Festive'],
    is_favorite: false,
  },

  // ACCESSORIES
  {
    name: 'Obsidian Minimalist Analog Watch',
    category: 'accessories',
    subcategory: 'watch',
    image_url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Black',
    secondary_colors: ['Silver', 'Charcoal'],
    pattern: 'Matte Dial',
    material: 'Stainless Steel & Leather',
    fit: 'Regular',
    style: 'Minimal',
    formality: 'Smart Casual',
    season: ['All-Season'],
    is_favorite: true,
  },
  {
    name: 'Cognac Full-Grain Leather Belt',
    category: 'accessories',
    subcategory: 'belt',
    image_url: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Cognac Brown',
    secondary_colors: ['Brass'],
    pattern: 'Solid',
    material: 'Full-Grain Leather',
    fit: 'Standard',
    style: 'Smart Casual',
    formality: 'Semi-Formal',
    season: ['All-Season'],
    is_favorite: true,
  },
  {
    name: 'Matte Black Classic Sunglasses',
    category: 'accessories',
    subcategory: 'sunglasses',
    image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    primary_color: 'Black',
    secondary_colors: ['Dark Green Lens'],
    pattern: 'Solid',
    material: 'Acetate',
    fit: 'Standard',
    style: 'Modern',
    formality: 'Casual',
    season: ['Summer', 'All-Season'],
    is_favorite: false,
  },
];
